### PR TITLE
[TASK] Upgrade for TYPO3 v10 compatibility

### PR DESCRIPTION
**Pull request by vertexvaar**
Hi,

thank you for providing this extension.
We still need to use it, but there is no version compatible with TYPO3 v10, so i updated the code with [TYPO3 Rector](https://github.com/sabbelasichon/typo3-rector), PHPStorm auto-reformat and a few manual changes.

I could run the unit tests, but i did not get the functional tests to work. Maybe they'll run in travis.

### CODE REVIEW

**Comment by tomasnorre** [comment]
Thanks for your work @vertexvaar, I'll take a look at this and give you feedback, so that we can have a new release done.

**Comment by tomasnorre** [comment]
I've just tested locally, I have a lot of functional tests failing with: 

```
37) Aoe\FeloginBruteforceProtection\Tests\Functional\System\ConfigurationTest::testExceptionOfGetFunction
Error: Class 'TYPO3\CMS\Core\Configuration\ExtensionConfiguration' not found
```
Does the `composer test:functional` work for you if you adjust the database credentials to a local db of yours? I run them against a local docker container with MySQL running in memory (for performance) 

Sorry that the travis isnt' well setup right now. We are working on switched to GitHub Actions, but didn't finish all extensions.

**Comment by vertexvaar** [comment]
Hi @tomasnorre 

thank you for having a look.

> Does the composer test:functional work for you
I tried hard but i didn't get these tests to work. I changed the credentials and tried to debug it, but i couldn't find the issue why the functional tests won't work.

Can you share your docker setup? That might help :)

**Comment by tomasnorre** [comment]
I have added the GitHub Actions to the master branch and seen that we also have a TYPO3V9 branch that is already 9LTS compatible. (Where I also added the github actions) 

Would you mind checking which branch your PR has most in common with? So that we base of it the right branch. 

I haven't paid attention to this earlier sorry. 

If you rebase you should have the Github actions available for helping with testing too.

**Comment by vertexvaar** [comment]
Hi @tomasnorre 

as requested, i rebased the changes. I also updated the GH actions CI, because i did only focus on TYPO v10. If this is going to be accepted, i'll test and add downwards compatibility.

I changed the PR's base to TYPO3v9, because your master and TYPO3v9 branch have diverged, which will result in merge conflicts.

**Comment by tomasnorre** [comment]
Thanks @vertexvaar I'll have a look at this one of the following days.

**Review by tomasnorre — APPROVED** [review]
@vertexvaar 

The code looks good to me, but doesn't look like it will be compatible with < 10 LTS. 

I'll need to do some cleanup in our branches before I can merge and release this. 
Hope you still have a little patient left.

**Comment by tomasnorre** [comment]
I'm sorry to bother you again @vertexvaar,

Looks like the TYPO3V9 branch was an old left over branch that wasn't removed as intended.
Would it be a lot of work for you to rebase based on master?

**Pull request merged**
